Repository finos/htc-grid, pull requests merged in 2021-08, with the labels that each got.

#17 Workshop initial
  docs/workshop/content/20_deploy_htc/80_deploying_htc/_index.en.md
  docs/workshop/content/40_deploying_a_pricing_engine/10_understanding_the_worker_code/_index.en.md
  docs/workshop/content/40_deploying_a_pricing_engine/20_deploying_the_pricing_engine/_index.en.md
  docs/workshop/content/40_deploying_a_pricing_engine/30_submitting_a_pricing_task/_index.en.md
Labels: documentation

#18 State Table abstraction layer
  deployment/grid/scripts/python/create_ddb_item.py
  deployment/grid/terraform/agent-config.tf
  deployment/grid/terraform/compute_plane/lambda_scaling.tf
  deployment/grid/terraform/compute_plane/variables.tf
  deployment/grid/terraform/control_plane/dynamodb.tf
  deployment/grid/terraform/control_plane/lambda.tf
  deployment/grid/terraform/control_plane/variables.tf
  deployment/grid/terraform/main.tf
  deployment/grid/terraform/variables.tf
  docs/workshop/content/20_deploy_htc/90_submitting_tasks/_index.en.md
  docs/workshop/content/30_monitoring/20_cloudwatch/_index.en.md
  docs/workshop/content/40_deploying_a_pricing_engine/30_submitting_a_pricing_task/_index.en.md
  source/client/python/api-v0.1/Makefile
  source/client/python/api-v0.1/api/connector.py
  source/client/python/api-v0.1/api/state_table_dynamodb.py
  source/client/python/api-v0.1/api/state_table_manager.py
  source/client/python/api-v0.1/tests/test_api_redis.py
  source/client/python/api-v0.1/tests/test_api_s3.py
  source/client/python/utils/utils/dynamodb_common.py
  source/client/python/utils/utils/state_table_common.py
  source/compute_plane/python/agent/agent.py
  source/compute_plane/python/lambda/scaling_metrics/scaling_metrics.py
  source/control_plane/python/lambda/cancel_tasks/cancel_tasks.py
  source/control_plane/python/lambda/get_results/get_results.py
  source/control_plane/python/lambda/submit_tasks/submit_tasks.py
  source/control_plane/python/lambda/ttl_checker/ttl_checker.py
Labels: kind/improvement, area/controlplane

#19 Replacing lambci by lambda-rie
  Makefile
  deployment/grid/charts/agent-htc-lambda/templates/deployment.yaml
  deployment/grid/charts/agent-htc-lambda/values.yaml
  deployment/grid/terraform/htc-agent/htc-agent.tf
  deployment/grid/terraform/main.tf
  deployment/image_repository/terraform/images_config.json
  deployment/image_repository/terraform/lambda_runtimes.tf
  deployment/image_repository/terraform/lambda_runtimes/Dockerfile.dotnet5.0
  deployment/image_repository/terraform/lambda_runtimes/Dockerfile.provided
  deployment/image_repository/terraform/lambda_runtimes/Dockerfile.python3.8
  deployment/image_repository/terraform/lambda_runtimes/lambda_entry_point.sh
  deployment/image_repository/terraform/lambda_runtimes/lambda_entry_point_provided.sh
  source/client/python/utils/utils/state_table_common.py
  source/compute_plane/python/agent/agent.py
  source/compute_plane/python/agent/requirements.txt
Labels: kind/improvement, area/computeplane

#20 using openAPI as a defintion of API Gateway
  Makefile
  README.md
  deployment/grid/terraform/compute_plane/auth.tf
  deployment/grid/terraform/compute_plane/eks_cluster.tf
  deployment/grid/terraform/compute_plane/grafana.tf
  deployment/grid/terraform/compute_plane/grafana_dashboard_k8s.yaml
  deployment/grid/terraform/compute_plane/influxd.tf
  deployment/grid/terraform/compute_plane/kubernetes-dashboard.json
  deployment/grid/terraform/compute_plane/main.tf
  deployment/grid/terraform/control_plane/api-gateway-private.tf
  deployment/grid/terraform/control_plane/api-gateway-public.tf
  deployment/grid/terraform/control_plane/main.tf
  deployment/grid/terraform/control_plane/openapi-private.tf
  deployment/grid/terraform/control_plane/openapi-public.tf
  docs/workshop/content/20_deploy_htc/80_deploying_htc/_index.en.md
  examples/client/python/requirements.txt
  examples/submissions/k8s_jobs/Dockerfile.Submitter
  requirements.txt
  source/client/python/api-v0.1/Makefile
  source/client/python/api-v0.1/api/connector.py
  source/client/python/api-v0.1/requirements.txt
  source/client/python/api-v0.1/tests/test_api_redis.py
  source/client/python/api-v0.1/tests/test_api_s3.py
  source/client/python/utils/Makefile
  source/client/python/utils/utils/state_table_common.py
  source/control_plane/openapi/Makefile
  source/control_plane/openapi/README.md
  source/control_plane/openapi/private/api_definition.yaml
  source/control_plane/openapi/public/api_definition.yaml
Labels: enhancement, kind/improvement, area/controlplane
